In [1]:
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np


In [2]:
# Understanding Machine Leraning (Supervised Learning)
# Garrith James (INTRODUCTION TO STATISTICAL LEARNING) - Recommended textbook
# Method of data analysis - using algorithms that learn from data.
# Data_acquisition > Data_Cleaning(Using_Keras) > Test_Data/Model&Training_Data cont. below
# cont. Model_Testing > Model_Deployment

In [3]:
# Understanding Classification metrics
# Result is either correct or incorrect. (We're gonna compare the predicted results to the right answers)
# Accuracy  - (no of correct predictions/no of predictions)
#           - not a good choice for unbalanced classes
# Recall - Ability of a model to find the relavant cases within a dataset.
# Precision - instances when the model predicted something as relevant vs the time it was actually relevant

# F1 Score 

# Confusion Matrix 


In [4]:
#############################################################################
#############################################################################
###########                      DEEP LEARNING                    ###########
# ###########################################################################
#############################################################################
# NEURAL NETWORKS - (Multiple Perceptron Network)
# Input layers - hidden Layers - output layers.
# 3 or more hidden network would be referred to as a "deep network"
# Sigmoid Function = f(x) or σ(x) = 1/ 1+e^(-x)
# cosh x = [e^(x) + e^(-x)]/2
# sinh x = [e^(x) - e^(-x)]/2
# tanh x = (sinh x/cosh x)
#
# ReLU max(0,x) - out puts the maximum value between the input and 0
#
#
# NEURONS - (Perceptron) Takes inputs and produces an output depending on the weights
# Input is multiplied by the weights and passed to an activation function 
# To prevent zero errors we use a bias value (could be a +1)
#
#
# COST FUNCTION - (Measure how far we are from the expected value)
# C = Σ(y-a)^2/n {due to the square we can get huge deviations from the real value}
# Cross Entropy C = (-1/n)Σ(y.ln(a) + (1-y).ln(1-a)) {reduces the error} 
#
#
# GRADIENT DESCENT (Optimization algorithm for finding the minimum value)
# We wanna choose a weight that minimizes the cost.
#
#
# BACK PROPAGATION 
#(calculates (using_calculus) the error contribution of each neuron to the final output)
#


In [5]:
from numpy import genfromtxt

In [6]:
data = genfromtxt('CV_Python/DATA/bank_note_data.txt', delimiter=',')

In [7]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [9]:
labels = data[:,4]


In [10]:
#eliminate the last column
features = data[:,0:4]

In [11]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [16]:
X = features
y = labels

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
# to make sure you get the same result use a random state 42 (42 is python's default)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
len(X_train)

919

In [20]:
len(X)

1372

In [21]:
len(X_test)

453

In [26]:
# standardize your data
from sklearn.preprocessing import MinMaxScaler

In [29]:
# fit() finds the min and the max then tranform the array passed based of the calculated min and max
scaler_object = MinMaxScaler()

In [30]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [32]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [34]:
scaled_X_train.max()

1.0000000000000002

In [35]:
X_train.max()

17.9274

In [36]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [37]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [38]:
#Compile the models
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [40]:
# Train the model
# Notice that it goes close to 99% accuracy
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.4109 - acc: 0.8879
Epoch 2/50
 - 0s - loss: 0.3914 - acc: 0.9086
Epoch 3/50
 - 0s - loss: 0.3721 - acc: 0.9119
Epoch 4/50
 - 0s - loss: 0.3538 - acc: 0.9227
Epoch 5/50
 - 0s - loss: 0.3358 - acc: 0.9325
Epoch 6/50
 - 0s - loss: 0.3183 - acc: 0.9369
Epoch 7/50
 - 0s - loss: 0.3025 - acc: 0.9478
Epoch 8/50
 - 0s - loss: 0.2865 - acc: 0.9478
Epoch 9/50
 - 0s - loss: 0.2716 - acc: 0.9543
Epoch 10/50
 - 0s - loss: 0.2581 - acc: 0.9587
Epoch 11/50
 - 0s - loss: 0.2447 - acc: 0.9597
Epoch 12/50
 - 0s - loss: 0.2322 - acc: 0.9641
Epoch 13/50
 - 0s - loss: 0.2212 - acc: 0.9608
Epoch 14/50
 - 0s - loss: 0.2098 - acc: 0.9619
Epoch 15/50
 - 0s - loss: 0.1996 - acc: 0.9619
Epoch 16/50
 - 0s - loss: 0.1903 - acc: 0.9630
Epoch 17/50
 - 0s - loss: 0.1815 - acc: 0.9630
Epoch 18/50
 - 0s - loss: 0.1735 - acc: 0.9652
Epoch 19/50
 - 0s - loss: 0.1656 - acc: 0.9630
Epoch 20/50
 - 0s - loss: 0.1583 - acc: 0.9663
Epoch 21/50
 - 0s - loss: 0.1512 - acc: 0.9663
Epoch 22/50
 - 0s - lo

In [42]:
#model.predict_classes(scaled_X_test)
# Produces the array of preditions

In [43]:
model.metrics_names

['loss', 'acc']

In [44]:
from sklearn.metrics import confusion_matrix,classification_report

In [48]:
prediction = model.predict_classes(scaled_X_test)

In [49]:
# since we already know the right answer (y_test) we can compare it to the predicted values
confusion_matrix(y_test,prediction)

array([[254,   3],
       [  3, 193]], dtype=int64)

In [51]:
# To see our results print out the classification report
# Shows we're getting really accurate results
print(classification_report(y_test,prediction))

             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99       257
        1.0       0.98      0.98      0.98       196

avg / total       0.99      0.99      0.99       453



In [52]:
#To save the model
model.save('myfirstmodel.hS')

In [53]:
# TO load the model....
from keras.models import load_model

new_model = load_model('myfirstmodel.hS')

In [54]:
new_model.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    