In [94]:
from keras.datasets import mnist

(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [95]:
train_images.shape

(60000, 28, 28)

In [96]:
train_labels.shape

(60000,)

In [97]:
train_labels[0]

5

In [64]:
from keras.utils import to_categorical
from keras import models,layers,Sequential

In [65]:
test_labels


array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [66]:
test_labels[0]


7

In [99]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [100]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [101]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [165]:
train_images = train_images.reshape(60000,28,28,1)

In [166]:
train_images.shape

(60000, 28, 28, 1)

In [159]:

test_labels.shape

(10000, 10)

In [167]:
test_images = test_images.reshape(10000,28,28,1)

In [168]:
test_images.shape

(10000, 28, 28, 1)

In [130]:
train_images.shape

(60000, 784)

In [109]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten

In [169]:
network = models.Sequential()

network.add(Conv2D(filters=32, kernel_size=(4,4),input_shape=(28,28,1), activation='relu'))
    


network.add(MaxPool2D(pool_size=(2,2)))
network.add(Flatten())

network.add(layers.Dense(512,activation='relu'))
network.add(layers.Dense(10,activation='softmax'))
network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

In [170]:
network.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_16 (Conv2D)           (None, 25, 25, 32)        544       
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 12, 12, 32)        0         
_________________________________________________________________
flatten_15 (Flatten)         (None, 4608)              0         
_________________________________________________________________
dense_51 (Dense)             (None, 128)               589952    
_________________________________________________________________
dense_52 (Dense)             (None, 10)                1290      
Total params: 591,786
Trainable params: 591,786
Non-trainable params: 0
_________________________________________________________________


In [171]:
network.fit(train_images,train_labels,epochs=7)

Epoch 1/7
60000/60000 [==============================] - 81s 1ms/step - loss: 14.5264 - acc: 0.0987
Epoch 2/7
60000/60000 [==============================] - 72s 1ms/step - loss: 14.5270 - acc: 0.0987
Epoch 3/7
60000/60000 [==============================] - 71s 1ms/step - loss: 14.5270 - acc: 0.0987
Epoch 4/7
60000/60000 [==============================] - 69s 1ms/step - loss: 14.5270 - acc: 0.0987
Epoch 5/7
60000/60000 [==============================] - 71s 1ms/step - loss: 14.5270 - acc: 0.0987
Epoch 6/7
60000/60000 [==============================] - 71s 1ms/step - loss: 14.5270 - acc: 0.0987
Epoch 7/7
60000/60000 [==============================] - 71s 1ms/step - loss: 14.5270 - acc: 0.0987


In [173]:
network.metrics_names

['loss', 'acc']

In [174]:
network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 3s 328us/step


[14.538521841430665, 0.098]

In [177]:
from sklearn.metrics import classification_report


In [181]:
predictions = network.predict_classes(test_images)

In [184]:
predictions[5]

0

In [190]:
test_labels[5].dtype

dtype('float32')

In [189]:
print(classification_report(test_labels,predictions))

ValueError: Mix type of y not allowed, got types {'binary', 'multilabel-indicator'}